In [1]:
import numpy as np

In [ ]:
# array : homogenous data structure
# data type : primitive data type- int, float, str
# derived data type- list tuple set dict
# data structure- stack, queue tress

a = np.array([1,2,3,4,5])
print(a.dtype)
print(a.shape)
print(a.ndim)
print(a.size)

In [11]:
b = np.linspace(1,100,10)

In [12]:
b.ndim

1

In [16]:
# 2d
np.linspace(1,100,10).reshape(5,2)

array([[  1.,  12.],
       [ 23.,  34.],
       [ 45.,  56.],
       [ 67.,  78.],
       [ 89., 100.]])

In [18]:
np.linspace(1,100,12).reshape(4,3) #2db

array([[  1.,  10.,  19.],
       [ 28.,  37.,  46.],
       [ 55.,  64.,  73.],
       [ 82.,  91., 100.]])

In [19]:
np.linspace(1,100,32).reshape(4,4,2) #3d

array([[[  1.        ,   4.19354839],
        [  7.38709677,  10.58064516],
        [ 13.77419355,  16.96774194],
        [ 20.16129032,  23.35483871]],

       [[ 26.5483871 ,  29.74193548],
        [ 32.93548387,  36.12903226],
        [ 39.32258065,  42.51612903],
        [ 45.70967742,  48.90322581]],

       [[ 52.09677419,  55.29032258],
        [ 58.48387097,  61.67741935],
        [ 64.87096774,  68.06451613],
        [ 71.25806452,  74.4516129 ]],

       [[ 77.64516129,  80.83870968],
        [ 84.03225806,  87.22580645],
        [ 90.41935484,  93.61290323],
        [ 96.80645161, 100.        ]]])

In [20]:
np.linspace(1,100,120).reshape(4,5,2,3)

array([[[[  1.        ,   1.83193277,   2.66386555],
         [  3.49579832,   4.32773109,   5.15966387]],

        [[  5.99159664,   6.82352941,   7.65546218],
         [  8.48739496,   9.31932773,  10.1512605 ]],

        [[ 10.98319328,  11.81512605,  12.64705882],
         [ 13.4789916 ,  14.31092437,  15.14285714]],

        [[ 15.97478992,  16.80672269,  17.63865546],
         [ 18.47058824,  19.30252101,  20.13445378]],

        [[ 20.96638655,  21.79831933,  22.6302521 ],
         [ 23.46218487,  24.29411765,  25.12605042]]],


       [[[ 25.95798319,  26.78991597,  27.62184874],
         [ 28.45378151,  29.28571429,  30.11764706]],

        [[ 30.94957983,  31.78151261,  32.61344538],
         [ 33.44537815,  34.27731092,  35.1092437 ]],

        [[ 35.94117647,  36.77310924,  37.60504202],
         [ 38.43697479,  39.26890756,  40.10084034]],

        [[ 40.93277311,  41.76470588,  42.59663866],
         [ 43.42857143,  44.2605042 ,  45.09243697]],

        [[ 45.92436975,  4

In [ ]:
# airthmetic operator
# +, -, *, /
a = np.array([45,56,24,34])

In [27]:
# comparison operator
# >, <, >=, <=, !=, ==
a > 50 # True, False
a[a>50]
#!=56
a[a!=56]
# even element:
a[a/2==0]

array([], dtype=int64)

In [ ]:
# numpy if, else:
# numpy array
# reshape
# +, _
# <, >,
# numpy if else

In [ ]:
num = 4
if num / 2 ==0:
    print ("even")
else:
    print("odd")

In [ ]:
even

In [28]:
np.where(a/2==0, "even", "odd"

SyntaxError: incomplete input (2394399582.py, line 1)

In [ ]:
# vectorize : 

In [30]:

ammount = np.array([20,30,40,50,100,140])

def func (value):
    if value>= 100:
        return value*0.8
    elif value >= 60 and value < 100:
        return value *0.6
    else:
        return value
d = np.vectorize(func)

#[1,2,3,4,5,5]
# ["odd", "even"]

In [31]:
def func (value):
    if value / 2 == 0:
        return "even"
    else:
        return "odd"
a = [1,2,3,4,5,6]
b = np. vectorise(func)
b(a)
    


SyntaxError: expected ':' (978588009.py, line 2)